# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:
  - test

build-and-test-job:       # This job runs in the build stage, which runs first.
  stage: test
  script:
    # Compile code
    - echo "[*] Compiling the code..."
    - cd task-4/src
    - javac *.java
    - jar cfm Solver.jar manifest.txt *.class
    # Execute benchmark
    - echo "[*] Executing benchmark ..."
    - cd ../vc-data-students
    - if [ ! -d 1-random ] || [ ! -d 2-social-networks ] || [ ! -d 3-medium-sized ]; then cp -r /home/master/vc-data/* . ; fi
    - chmod +x benchmark-fast.sh verify verifier.py
    - ./benchmark-fast.sh "java -jar ../src/Solver.jar"
    # Verify CSV file
    - echo "[*] Verifing result in CSV file ..."
    - echo "Solved instances:" $(grep "OK" $(find . -name "*.csv" | tail -n 1) | wc -l)
    - if [ $(grep "OK" $(find . -name "*.csv" | tail -n 1) | wc -l) -eq 0 ]; then echo "[ERROR] No 'OK' entries found in latest CSV file. There must be something wrong!"; exit 1; fi
    - if [ $(grep "Not a VC:" $(find . -name "*.csv" | tail -n 1) | wc -l)  -gt 0 ]; then echo "[ERROR] Some tests failed with 'Not a VC:' (in column VC-check). Please fix them before commiting!"; exit 1; fi
    - echo "[*] Benchmark done. All tests passed!"
